name: HungerCraftThirst
main: ablbebxb.hungercraftthirst.HungerCraftThirst
version: 1.1

commands:
  checkthirst:
    description: Tells the sender his thirst level
    usage: /checkthirst
    permission: thirster
    permission-message: You can't get thirsty, so don't worry about it
  thirst:
    description: Shows the sender his thirst level
    usage: /thirst
    permission: thirster
    permission-message: You can't get thirsty, so don't worry about it

permissions:
  thirster:
    decription: anyone who wants to get thirsty, generally combatants
    default: false
